apps/bitcoin_crypto/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^settings/', SettingsView.as_view(), name='settings'),
    url(r'^exchange-rate/$', ExchangeRateView.as_view(), name='exchange_rate'),
    url(r'^transactions/$', TransactionListView.as_view(), name='transaction_list'),

    #wallets
    url(r'^wallets/$', WalletsView.as_view(), name='wallets'),
    url(r'^sgd-wallets/$', SGDWalletsView.as_view(), name='sgd_wallets'),
    url(r'^update-sgd-wallet/(?P<pk>\d+)/$', AddSGDView.as_view(), name='update_sgd_wallet'),

    url(r'^sendbcoin/$', SendBTransactionView.as_view(), name='sendbtccoin'),
    url(r'^sendtcoin/$', SendTTransactionView.as_view(), name='sendtxchcoin'),
    url(r'^sendconfirm/$', SendConfirmView.as_view(), name='sendconfirm'),
    url(r'^confirm-withdrawal/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        SendEmailConfirmView.as_view(), name='confirm_withdrawal'),
    url(r'^pending-transactions/$', PendingTransactionListView.as_view(), name='pending_transactions'),
    url(r'^confirm-pending-transaction/(?P<pk>\d+)/$', ConfirmPendingTransactionView.as_view(), name='confirm_pending_transaction'),
    url(r'^reject-pending-transaction/(?P<pk>\d+)/$', RejectPendingTransactionView.as_view(), name='reject_pending_transaction'),

    url(r'^all-user-wallet-accounts/$', GetAllUserAddress.as_view(), name='get_all_wallet_users'),
    url(r'^transaction-records/$', TransactionRecordView.as_view(template_name="bitcoin/transaction_record.html"), name='transaction_record'),

    url(r'^set-minimum-limit/$', SetMinimunLimitBTC.as_view(), name='set_minimum_limit'),
    url(r'^set-market-limit/$', SetMarketLimit.as_view(), name='set_market_limit'),
    url(r'^wallet-to-vault/$', WalletToVault.as_view(), name='wallet_to_vault'),
    url(r'^dispute-solve/$', SolveDispute.as_view(), name='dispute_system'),
    url(r'^dispute-raise/$', RaiseDisputeView.as_view(), name='raise_dispute'),
    url(r'^dispute-confirm/$', ConfirmDisputeView.as_view(), name='dispute_confirm'),
    url(r'^dispute-list-my/$', MyListDisputeView.as_view(), name='my_list_dispute'),
    url(r'^dispute-list/$', ListDisputeProcessingView.as_view(), name='list_dispute'),
    url(r'^dispute-approve-list/$', ListDisputeApproveView.as_view(), name='dispute_approve_list'),
    url(r'^dispute-processing-list/$', ListDisputeProcessingView.as_view(), name='dispute_processing_list'),
    url(r'^dispute-rejected-list/$', ListDisputeRejectedView.as_view(), name='dispute_rejected_list'),
    url(r'^dispute-detail/(?P<pk>\d+)/$', DisputeDetailView.as_view(), name='dispute_detail'),
    url(r'^dispute-approve/(?P<pk>\d+)/$', DisputeApproveView.as_view(), name='dispute_approve'),
    url(r'^dispute-reject/(?P<pk>\d+)/$', DisputeRejectView.as_view(), name='dispute_reject'),
    url(r'^dispute-resubmission/(?P<pk>\d+)/$', DisputeResubmitView.as_view(), name='dispute_resubmission'),
    url(r'^confirm-wallet-to-vault/$', ConfirmWalletToVault.as_view(), name='confirm_wallet_to_vault'),
    
    url(r'^vault-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        WalletToVaultEmailConfirm.as_view(), name='vault_confirm'),
    url(r'^vault-transactions/$', VaultTransactionListView.as_view(), name='vault_transaction_list'),
    url(r'^vault-to-wallet/$', VaultToWalletView.as_view(), name='vault_to_wallet'),
    url(r'^vault-list/$', ListVaultView.as_view(), name='vault_list'),
    
    #pending order urls
    url(r'^cancel-pending-order/(?P<pk>\d+)/$', CancelPendingOrderView.as_view(), name='cancel_pending_order'),

    # records urls
    url(r'^get-user-balance/', GetUserBalanceTransactionView.as_view(), name='get_user_balance'),

    # order urls
    url(r'^stop-limit-order/$', OrderView.as_view(), name='stop_limit_order'),
    url(r'^depthchart/$', AjaxDepthChartView.as_view(), name='depthchart'),
    url(r'^buy-order-list/$', BuyOrderList.as_view(), name='buy_order_list'),
    url(r'^sell-order-list/$', SellOrderList.as_view(), name='sell_order_list'),
    url(r'^delete-order/(?P<pk>\d+)/$', DeleteOrderView.as_view(), name='delete_order'),

    # accept order urls
    url(r'^accept-order/', AcceptOrderView.as_view(), name='accept_order'),
    url(r'^confirm-order/', ConfirmFiatTransactionsView.as_view(), name='confirm_fiat_pendings'),
    url(r'^confirm-request-order/', ConfirmRequestFiatTransactionsView.as_view(), name='confirm_request_pendings'),
    url(r'^cancel-request-order/', CancelRequestFiatTransactionsView.as_view(), name='cancel_requestcrypto_order'),
    url(r'^cancel-request-fiat-order/', CancelAcceptFiatTransactionsView.as_view(), name='cancel_requestfiat_order'),
    url(r'^update-otc-order/', UpdateOtcOrderView.as_view(), name='update_otc_order'),

    #notification urls
    url(r'^notifications/$', NotificationListView.as_view(), name='notifications'),

    #report
    url(r'^report/$', DownloadReport.as_view(), name='report'),
    url(r'^ajax-order-book/$', AjaxOrderBookView.as_view(), name='ajax_order_book'),
]

cryptocurrency/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.static import serve
from apps.bitcoin_crypto.views import IndexView, WelcomeView, OtcWelcomeView
from .utils import ProtectServe

from background_task import background

@background()
def check_table():
    # lookup user by id and send them a message
    # user = User.objects.filter()
    print("this is check table scheduler ======== ")


# check_table(repeat=5)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crypto/', include('apps.bitcoin_crypto.urls', namespace='coins')),
    url(r'^fees/', include('apps.fees.urls', namespace='fees')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^auth/', include('apps.authentication.urls')),
    url(r'^dashboard/', WelcomeView.as_view(), name='welcome'),
    url(r'^otcdashboard/', OtcWelcomeView.as_view(), name='welcomeotc'),
    url(r'^exchange/', TemplateView.as_view(template_name='theme/exchange.html'), name='exchange'),
    url(r'^$', OtcWelcomeView.as_view(), name='index'),
    # url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], ProtectServe.as_view(), {'document_root': settings.MEDIA_ROOT}),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/bitcoin_crypto/models.py
from django.db import models
from apps.authentication.models import User
from django.contrib.sites.models import Site
from decimal import Decimal


class WalletAddress(models.Model):
    address = models.CharField(max_length=500, blank=True, default="")

    def __str__(self):
        return self.address

class CryptoCurrency(models.Model):
    basepair = models.CharField(max_length=500, blank=True, default="")

    def __str__(self):
        return self.basepair

class Fiat(models.Model):
    topair = models.CharField(max_length=500, blank=True, default="")

    def __str__(self):
        return self.topair


class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, blank=True, default="")
    addresses = models.ManyToManyField(WalletAddress)
    private = models.CharField(max_length=500, blank=True, default="")
    public = models.CharField(max_length=500, blank=True, default="")
    words = models.CharField(max_length=500, blank=True, default="")

    def __str__(self):
        return self.name + " " + self.user.username


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.CharField(blank=False, max_length=200)
    balance = models.CharField(blank=True, max_length=20)
    currency = models.CharField(blank=True, max_length=20)
    transaction_id = models.CharField(blank=True, max_length=200)
    transaction_to = models.CharField(blank=True, max_length=200)
    transaction_type = models.CharField(blank=True, max_length=200)
    pending = models.BooleanField(default=True)
    invalid = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)
    transaction_fee = models.CharField(blank=True, max_length=200, default=0)
    mining_fee = models.CharField(blank=True, max_length=200, default=0)
    #last modification of object when transaction confirmed then datetime is auto_now
    date = models.DateTimeField(auto_now=True)

    def transaction_fee_except_mining_fees(self):
        try:
            transaction_fee = Decimal(self.transaction_fee)
        except:
            transaction_fee = 0

        try:
           mining_fee =  Decimal(self.mining_fee)
        except:
            mining_fee = 0

        if transaction_fee > 0:
            transaction_fee = transaction_fee - mining_fee

        return transaction_fee


    def __str__(self):
        return self.user.username


class PendingTransactions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.CharField(max_length=200)
    currency = models.CharField(max_length=20)
    transaction_to = models.CharField(max_length=200)
    transaction_fee = models.CharField(blank=True, max_length=200)

    def __str__(self):
        return self.user.username


class VaultWallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(blank=False, max_length=200, unique=True)
    name = models.CharField(max_length=20, blank=True, default="")
    addresses = models.ManyToManyField(WalletAddress) 
    private = models.CharField(max_length=500, blank=True, default="")
    public = models.CharField(max_length=500, blank=True, default="")
    words = models.CharField(max_length=500, blank=True, default="")
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username


class VaultTransaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.CharField(blank=False, max_length=200)
    balance = models.CharField(blank=True, max_length=20)
    mining_fee = models.CharField(blank=True, max_length=200, default='0')
    currency = models.CharField(blank=True, max_length=20)
    transaction_id = models.CharField(blank=True, max_length=200)
    transaction_to = models.CharField(blank=True, max_length=200)
    transaction_from = models.CharField(blank=True,default='', max_length=200)
    transaction_type = models.CharField(blank=True, max_length=200, default='to_vault')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class MinimunCoin(models.Model):
    site = models.OneToOneField(Site, on_delete=models.CASCADE)
    btc_limit = models.CharField(max_length=200,default='0.0')
    user_alert = models.BooleanField(default=True)
    low_limit_alert = models.BooleanField(default=True)


class MarketLimit(models.Model):
    min_price_limit = models.CharField(max_length=200,default='0.0')
    max_price_limit = models.CharField(max_length=200,default='0.0')
    min_amount_limit = models.CharField(max_length=200,default='0.0')
    max_amount_limit = models.CharField(max_length=200,default='0.0')

class WatchOnlyAddress(models.Model):
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.address


class SGDWallet(models.Model):
    user = models.ForeignKey(User)
    amount = models.FloatField(default=0)

    def __str__(self):
        return self.user.username


class OrderBook(models.Model):
    ORDER_CHOICES = (
        ('0', 'Buy'),
        ('1', 'sell')
    )
    ORDER_MODE = (
        ('0', 'market'),
        ('1', 'limit'),
        ('2', 'stop-limit')
    )

    user = models.ForeignKey(User, related_name='Users')
    exchange_form = models.CharField(max_length=5)
    exchange_to = models.CharField(max_length=5)
    amount = models.FloatField()
    price = models.FloatField()
    limit = models.FloatField()
    is_otc = models.CharField(max_length=2)
    order_type = models.CharField(choices=ORDER_CHOICES, max_length=2)
    order_mode = models.CharField(choices=ORDER_MODE, max_length=2)
    order_time = models.DateTimeField(auto_now_add=True)
    trade_status = models.BooleanField(default=False)
    coins_covered = models.FloatField(default=0)
    trading_fee = models.FloatField(default=0)
    canceled = models.BooleanField(default=False)
    maker = models.BooleanField(default=False)



    def __str__(self):
        return self.user.username

class PendingOrder(models.Model):
    user = models.ForeignKey(User, related_name='pending_order_user')
    pending_amount = models.FloatField()
    order = models.ForeignKey(OrderBook, related_name='pending_order', on_delete=models.CASCADE)
    order_time = models.DateTimeField(auto_now_add=True)
    is_pending = models.BooleanField(default=True)

class OrderMatchingHistory(models.Model):
    processing_order = models.ForeignKey(OrderBook, related_name='processing_order')
    matched_order = models.ForeignKey(OrderBook, related_name='matched_order')
    matching_price = models.FloatField(default=0)
    coins_covered = models.FloatField(default=0)
    trading_fee = models.FloatField(default=0)
    order_matching_time = models.DateTimeField(auto_now_add=True)


class ExchangeTaxRates(models.Model):
    previous_rate = models.FloatField(default=None, null=True, blank=True)
    current_rate = models.FloatField(default=0)
    updated_on = models.DateField(auto_now_add=True, blank=True)
    update_by = models.ForeignKey(User)

    def __str__(self):
        return self.update_by.username



class Notification(models.Model):
    date =  models.DateTimeField(auto_now=True)
    user = models.ManyToManyField(User, through='NotificationUser')
    notification = models.TextField(max_length=128)

    def __str(self):
        return self.notification


class NotificationUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE)
    is_readed = models.BooleanField(default=False)
    is_pending_notification = models.BooleanField(default=False)


class TransactionTracker(models.Model):
    previous_transaction_count = models.CharField(max_length=128)

class ConfirmFiatTransaction(models.Model): #OTC part transaction
    amount = models.FloatField()
    crypto_amount = models.FloatField()
    fiat_type = models.CharField(max_length=5)
    crypto_type = models.CharField(max_length=5)
    receive_address = models.CharField(max_length=128)
    is_confirm = models.BooleanField(default=False)
    is_cancel = models.BooleanField(default=False)
    receiver = models.ForeignKey(User, related_name='user_fiat_receiver', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='user_fiat_sender', on_delete=models.CASCADE)
    order = models.ForeignKey(OrderBook, on_delete=models.CASCADE)
    pending_order = models.ForeignKey(PendingOrder, on_delete=models.CASCADE)
    def __str__(self):
        return self.sender.username+"->"+self.receiver.username

class ConfirmCrytpoRequest(models.Model): #OTC part transaction
    amount = models.FloatField()
    crypto_amount = models.FloatField()
    fiat_type = models.CharField(max_length=5)
    crypto_type = models.CharField(max_length=5)
    is_confirm = models.BooleanField(default=False)
    is_cancel = models.BooleanField(default=False)
    receiver = models.ForeignKey(User, related_name='user_crypto_receiver', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='user_crypto_sender', on_delete=models.CASCADE)
    order = models.ForeignKey(OrderBook, on_delete=models.CASCADE)

class OrderCoverTransaction(models.Model): #CTC part transaction
    amount = models.FloatField()
    user = models.ForeignKey(User, related_name='order_bidder', on_delete=models.CASCADE)
    order = models.ForeignKey(OrderBook, on_delete=models.CASCADE)

class DisputeUpload(models.Model):
    user = models.ForeignKey(User, related_name='defender_user_details')
    user_phonenumber = models.CharField(max_length=20, blank=True, default="")
    user_email = models.CharField(max_length=50, blank=True, default="")
    front_page = models.ImageField()
    description = models.TextField()
    client_phonenumber = models.CharField(max_length=20, blank=True, default="")

templates/bitcoin/dispute_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Dispute" %}{% endblock %}

{% block content %}
<div class="profile">
    <div class="container">
        <div class="row m0">
            {% if not request.user.is_superuser %}
            <div class="col-sm-8">
                <div class="profile-top">
                    <h4 class="m40"><b>{% trans "Your Dispute status" %}</b></h4>
                    {% if disputeDetail.dispute_status == 'approved' %}
                        <button class="btn-main btn m20 "> <i class="fas fa-check" style="color: #0fd800;"></i> {% trans "Approved" %}</button>
                    {% elif disputeDetail.dispute_status == 'rejected' %}
                        <button class="btn-main btn m20 "> <i class="fas fa-close" style="color: red;"></i> {% trans "Rejected" %}</button>
                    {% elif disputeDetail.dispute_status == 'processing' %}
                        <button class="btn-main btn m20 "> <i class="fas fa-sync" style="color: #f3bc18;"></i> {% trans "Processing" %}</button>
                    {% endif %}
                </div>
            </div>
            {% endif %}
            <div class="col-sm-12">
                <div class="profile-bottom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#home">{% trans "Dispute details" %}</a></li>
                        <li><a data-toggle="tab" href="#menu1">{% trans "Documents" %}</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="home" class="tab-pane fade in active">
                            <div class="row m0">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="grey">{% trans "User Name" %}</label>
                                        <h3 class="m0">{{user_profile.full_name}}</h3>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="grey">{% trans "User Phone Number" %}</label>
                                        <h3 class="m0">{{user.phone_number}}</h3>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="grey">{% trans "User Email" %}</label>
                                        <h3 class="m0">{{user.email}}</h3>
                                    </div>
                                </div>
                            </div>
                            {% if not client_invalid %}
                                <div class="row m0">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label class="grey">{% trans "Client Name" %}</label>
                                            <h3 class="m0">{{client_profile.full_name}}</h3>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label class="grey">{% trans "Client Email" %}</label>
                                            <h3 class="m0">{{client.email}}</h3>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label class="grey">{% trans "Client Phonenumber" %}</label>
                                            <h3 class="m0">{{disputeDetail.client_phonenumber}}</h3>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                            {% if client_invalid %}
                                <div class="row m0">
                                    <br/>
                                    <div class="col-sm-6">
                                            <h3 class="m0" style="color: red">{% trans "Provided Client PhoneNumber is invalid" %}</h3>
                                    </div>
                                </div>
                            {% endif %}
                            <div class="row m0">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label class="grey">{% trans "Description" %}</label>
                                        <h3 class="m0">{{disputeDetail.description}}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="menu1" class="tab-pane fade">
                            <div class="row m0">
                                <h2 class="Ubuntu mf15">{% trans "Photo" %}</h2>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <img src="{{disputeDetail.front_page.url}}" width="100%">
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div style="text-align:right; padding:20px;">
                    {% if request.user.is_superuser %}
                        <a href="{% url 'coins:list_dispute' %}" style="width:200px;margin-right:15px;" class="btn btn-success">{% trans "Back To Dispute List" %}</a>
                        {% if user.kyc_verified == 'processing' %}
                            <a href="{% url 'coins:dispute_approve' pk=disputeDetail.pk %}" style="width:200px" class="btn btn-primary">{% trans "Approve" %}</a>
                        {% endif %}

                        {% if not user.kyc_verified == 'rejected' %}
                        <a href="{% url 'coins:dispute_reject' pk=disputeDetail.pk %}" style="width:200px" class="btn btn-danger">{% trans "Reject" %}</a>
                        {% endif %}
                        
                    {% else %}
                        <a href="{% url 'coins:my_list_dispute' %}" style="width:200px;margin-right:15px;" class="btn btn-success">{% trans "Back To Dispute List" %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

{% block script %}
  <script>
    $('#home,#tag').on('hover focus',function(){
        alert();
    })
  </script>
{% endblock %}

templates/bitcoin/list_dispute.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Dispute Details" %}{% endblock %}

{% block content %}

<style>
    li.active:hover a{
        background-color: #f9f9f9 !important;
        border: #f9f9f9 !important;
    }
    .nav-tabs>li{
        margin-bottom: 0px;
    }
</style>

<div class="kyc">
    <div class="container">
        <h2 class="Ubuntu mf15">{% trans "Dispute Details" %}</h2>
        <div class="row m10">
            {% if messages %}
                    <div class="alert alert-success" style="position: relative;">
                      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {% for message in messages %}
                  {{ message }}
                {% endfor %}
              </div>
            {% endif %}
        </div>
        <div class="row m0">
            <div class="col-sm-12">
                <div class="kyc-details">
                    <ul class="nav nav-tabs">
                        <li class="process {% if processing %}active{% endif %}"><a href="{% url 'coins:dispute_processing_list' %}"></i> <span>{% trans "Processing" %}</span> </a></li>
                        <li class="process {% if active %}active{% endif %}"><a href="{% url 'coins:dispute_approve_list' %}"><span>{% trans "Approved" %}</span></a></li>
                        <li class="process {% if rejected %}active{% endif %}"><a href="{% url 'coins:dispute_rejected_list' %}"><span>{% trans "Rejected" %}</span></a></li>
                    </ul>
                   <div class="tab-content">
                        <div class="">
                            {% if processing %}
                                {% for object in dispute_processing_list %}
                                    <div class="row m0 ">
                                        <div class="col-sm-12 kyc-wrap">
                                            <div class="col-sm-8">
                                                <h4 class="m15"> <i class="fa fa-circle fa-0x processing"></i> {% trans "User Phonenumber:" %}{{object.user_phonenumber}} {% trans "User Email:" %}{{object.user_email}}</h4>
                                            </div>
                                            <div align="center" class="col-sm-4">
                                                <a href="{% url 'coins:dispute_detail' pk=object.pk %}" class="btn btn-disable"> {% trans "View" %}  </a>
                                                <a href="{% url 'coins:dispute_approve' pk=object.pk %}" class="btn btn-disable"> {% trans "Accept" %}  </a>
                                            </div>
                                        </div>
                                    </div>
                                {% empty %}
                                    <div class="row m0 " align="middle">
                                        <div class="col-sm-12 kyc-wrap">
                                        {% trans "No Record Found" %}
                                        </div>
                                    </div>
                                {% endfor %}
                            {% elif approved %}
                                {% for object in dispute_approved_list %}
                                    <div class="row m0 ">
                                        <div class="col-sm-12 kyc-wrap">
                                            <div class="col-sm-8">
                                                <h4 class="m15"> <i class="fa fa-circle fa-0x processing"></i> {{object.user_email}} {{object.user_phonenumber}}</h4>
                                            </div>
                                            <div align="center" class="col-sm-4">
                                                <a href="{% url 'coins:dispute_detail' pk=object.pk %}" class="btn btn-disable"> {% trans "View" %}  </a>
                                                <a href="{% url 'coins:dispute_resubmission' pk=object.pk %}" class="btn btn-disable"> {% trans "Resubmission" %} </a>
                                            </div>
                                        </div>
                                    </div>
                                {% empty %}
                                    <div class="row m0 " align="middle">
                                        <div class="col-sm-12 kyc-wrap">
                                        {% trans "No Record Found" %}
                                        </div>
                                    </div>
                                {% endfor %}
                            {% elif rejected %}
                                {% for object in dispute_rejected_list %}
                                    <div class="row m0 ">
                                        <div class="col-sm-12 kyc-wrap">
                                            <div class="col-sm-8">
                                                <h4 class="m15"> <i class="fa fa-circle fa-0x processing"></i> {{object.user_email}} {{object.user_phonenumber}}</h4>
                                            </div>
                                            <div align="center" class="col-sm-4">
                                                <a href="{% url 'coins:dispute_detail' pk=object.pk %}" class="btn btn-disable"> {% trans "View" %}  </a>
                                                <a href="{% url 'coins:dispute_resubmission' pk=object.pk %}" class="btn btn-disable"> {% trans "Resubmission" %} </a>
                                            </div>
                                        </div>
                                    </div>
                                {% empty %}
                                    <div class="row m0 " align="middle">
                                        <div class="col-sm-12 kyc-wrap">
                                        {% trans "No Record Found" %}
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/bitcoin/notification_email.html
{% load i18n %}
<h4>{% trans "Hi" %} {{ user.username }},</h4> </br>
<p><b>{{notification_txt|safe}}</b></p>

<p>{% trans "Sincerely" %},</p>
<p>Tixonxchange </p>
<p>http://tixon.exchange</p>

templates/bitcoin/notifications.html
{% extends 'base.html' %}  
{% load static %} 
{% load i18n %}

{% block title %}{% trans "Notifications" %}{% endblock %}

{% block content %}
<div class="trans">
	<div class="container">
		<div class="row m0">
			<div class="col-sm-12">
				<div class="trans-details">
					<div class="tab-content">
						{% if notifications.0 %}
						<div class="table-responsive">
							<table class="table table_template darklinks table-bordered table-hover" id="timetable">
								<thead>
									<tr>
										<th>{% trans "Date" %}</th>
										<th>{% trans "Message" %}</th>
									</tr>
								</thead>
								<tbody>

									{% for obj in notifications %}
									<tr {% if forloop.counter <= notification_count %} style="background-color: #f6ebeb" {% endif %}>
										<td>{{obj.date}}</td>
										<td>{{obj.notification|safe}}</td>

									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
						{% else %}
						<p class="text-center"><b> {% trans "No Notifications" %}</b></p>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

{% block script %}
{% endblock %}

{% block footer %}
{% endblock %}