apps/authentication/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from apps.authentication.views import * 




urlpatterns = [
    url(r'^signup/', RegistrationView.as_view(), name='signup'),
    url(r'^get-started/', GetStartedView.as_view(), name='get_started'),
    url(r'^login/$', CustomLoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page= '/'), name='logout'),\
    url(r'email-confirmation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', ConfirmSignUpView.as_view(), name="email_confirmation"),
    url(r'^password_reset/$', CustomPasswordResetView.as_view(
        template_name='authentication/password_reset_confirm.html', 
        html_email_template_name='authentication/password_reset_email.html',
        subject_template_name='authentication/password_reset_subject.txt',), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_rest_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        CustomPasswordResetConfirmView.as_view(template_name='authentication/password-reset.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password-reset-done.html'), name='password_reset_complete'),
    url(r'^password_change/$', PasswordChangeView.as_view(template_name='authentication/password-change.html'), name='password_change'),
    url(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password-reset-done.html'), name='password_change_done'),
    
    url(r'^otp/$', TwoFactorAuthenticationView.as_view(), name='otp'),
    url(r'^check-otp/$', CheckTwoFactorAuthenticationView.as_view(), name='check_otp'),
    url(r'^send-otp/$', SendOTP.as_view(), name='send_otp'),

    url(r'^desable-otp/$', DesableMobileOtp.as_view(), name='desable_otp'),

    url(r'^kyc-upload/$', KYCUploadView.as_view(), name='kyc_upload'),
    url(r'^get-zip-regx/$', ZipRgxView.as_view(), name='get_zip_rgx'),
    url(r'^kyc-confirm/$', ConfirmKYCUpload.as_view(), name='kyc_confirm'),
    url(r'^kyc-detail/(?P<pk>\d+)/$', KYCDetailView.as_view(), name='kyc_detail'),
    url(r'^kyc-list/$', KYCProcessingListView.as_view(), name='kyc_list'),
    url(r'^active-list/$', KYCActiveListView.as_view(), name='active_list'),
    url(r'^rejected-list/$', KYCRejectedListView.as_view(), name='rejected_list'),
    url(r'^kyc-approve/(?P<pk>\d+)/$', KYCApproveView.as_view(), name='kyc_approve'),
    url(r'^kyc-reject/(?P<pk>\d+)/$', KYCRejectView.as_view(), name='kyc_reject'),
    url(r'^kyc-resubmission/(?P<pk>\d+)/$', KYCResubmitView.as_view(), name='kyc_resubmission'),

    url(r'^verify-2fa/$', VerifyGoogle2fa.as_view(), name='verify_2fa'),
    url(r'^enable-2fa/$', EmableGoogle2fa.as_view(), name='enable_2fa'),
    url(r'^ajax-enable-2fa/$', AjaxEmableGoogle2fa.as_view(), name='ajax_enable_2fa'),
    url(r'^desable-2fa/$', DesableGoogle2fa.as_view(), name='desable_2fa'),
    url(r'^enable-otp/$', Ajax2FAEnable.as_view(), name='enable_otp'),
    url(r'^validate-otp/$', AjaxOTPValidation.as_view(), name='validate_otp'),
    url(r'^ajax-disable-2fa/$', AjaxSend2FADisbleOTP.as_view(), name='disable_sms'),
    url(r'^upadte-phone-number/$', UpdateMobileNumber.as_view(), name='upadte_phone_number'),
    url(r'^ajax-upadte-phone-number/$', AjaxUpdateMobileNumber.as_view(), name='ajax_upadte_phone_number'),

    url(r'^add-bank-account/$', BankAccountView.as_view(), name='add_bank_account'),
    url(r'^add-wechat-account/$', WechatAccountView.as_view(), name='add_wechat_account'),
    url(r'^add-alipay-account/$', AlipayAccountView.as_view(), name='add_alipay_account'),
    url(r'^add-paypal-account/$', PaypalAccountView.as_view(), name='add_paypal_account'),
    url(r'^edit-bank-account/(?P<pk>\d+)/$', EditBankAccountView.as_view(), name='edit_bank_account'),
    url(r'^edit-paypal-account/(?P<pk>\d+)/$', EditPaypalAccountView.as_view(), name='edit_paypal_account'),
    url(r'^edit-wechat-account/(?P<pk>\d+)/$', EditWechatAccountView.as_view(), name='edit_wechat_account'),
    url(r'^edit-alipay-account/(?P<pk>\d+)/$', EditAlipayAccountView.as_view(), name='edit_alipay_account'),
    url(r'^remove-bank-account/$', RemoveBankAccountView.as_view(), name='remove_bank_account'),
    url(r'^remove-wechat-account/$', RemoveWechatAccountView.as_view(), name='remove_wechat_account'),
    url(r'^remove-alipay-account/$', RemoveAlipayAccountView.as_view(), name='remove_alipay_account'),
    # url(r'^edit-paypal-account/(?P<pk>\d+)/$', RemovePaypalAccountView.as_view(), name='remove_paypal_account'),
    # url(r'^edit-wechat-account/(?P<pk>\d+)/$', RemoveWechatAccountView.as_view(), name='remove_wechat_account'),
    # url(r'^edit-alipay-account/(?P<pk>\d+)/$', RemoveAlipayAccountView.as_view(), name='remove_alipay_account'),
    url(r'^contact-us/$', ContactUsView.as_view(), name='contact_us'),
]

apps/bitcoin_crypto/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^settings/', SettingsView.as_view(), name='settings'),
    url(r'^exchange-rate/$', ExchangeRateView.as_view(), name='exchange_rate'),
    url(r'^transactions/$', TransactionListView.as_view(), name='transaction_list'),

    #wallets
    url(r'^wallets/$', WalletsView.as_view(), name='wallets'),
    url(r'^sgd-wallets/$', SGDWalletsView.as_view(), name='sgd_wallets'),
    url(r'^update-sgd-wallet/(?P<pk>\d+)/$', AddSGDView.as_view(), name='update_sgd_wallet'),

    url(r'^sendbcoin/$', SendBTransactionView.as_view(), name='sendbtccoin'),
    url(r'^sendtcoin/$', SendTTransactionView.as_view(), name='sendtxchcoin'),
    url(r'^sendconfirm/$', SendConfirmView.as_view(), name='sendconfirm'),
    url(r'^confirm-withdrawal/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        SendEmailConfirmView.as_view(), name='confirm_withdrawal'),
    url(r'^pending-transactions/$', PendingTransactionListView.as_view(), name='pending_transactions'),
    url(r'^confirm-pending-transaction/(?P<pk>\d+)/$', ConfirmPendingTransactionView.as_view(), name='confirm_pending_transaction'),
    url(r'^reject-pending-transaction/(?P<pk>\d+)/$', RejectPendingTransactionView.as_view(), name='reject_pending_transaction'),

    url(r'^all-user-wallet-accounts/$', GetAllUserAddress.as_view(), name='get_all_wallet_users'),
    url(r'^transaction-records/$', TransactionRecordView.as_view(template_name="bitcoin/transaction_record.html"), name='transaction_record'),

    url(r'^set-minimum-limit/$', SetMinimunLimitBTC.as_view(), name='set_minimum_limit'),
    url(r'^set-market-limit/$', SetMarketLimit.as_view(), name='set_market_limit'),
    url(r'^wallet-to-vault/$', WalletToVault.as_view(), name='wallet_to_vault'),
    url(r'^dispute-solve/$', SolveDispute.as_view(), name='dispute_system'),
    url(r'^dispute-raise/$', RaiseDisputeView.as_view(), name='raise_dispute'),
    url(r'^dispute-confirm/$', ConfirmDisputeView.as_view(), name='dispute_confirm'),
    url(r'^dispute-list-my/$', MyListDisputeView.as_view(), name='my_list_dispute'),
    url(r'^dispute-list/$', ListDisputeProcessingView.as_view(), name='list_dispute'),
    url(r'^dispute-approve-list/$', ListDisputeApproveView.as_view(), name='dispute_approve_list'),
    url(r'^dispute-processing-list/$', ListDisputeProcessingView.as_view(), name='dispute_processing_list'),
    url(r'^dispute-rejected-list/$', ListDisputeRejectedView.as_view(), name='dispute_rejected_list'),
    url(r'^dispute-detail/(?P<pk>\d+)/$', DisputeDetailView.as_view(), name='dispute_detail'),
    url(r'^dispute-approve/(?P<pk>\d+)/$', DisputeApproveView.as_view(), name='dispute_approve'),
    url(r'^dispute-reject/(?P<pk>\d+)/$', DisputeRejectView.as_view(), name='dispute_reject'),
    url(r'^dispute-resubmission/(?P<pk>\d+)/$', DisputeResubmitView.as_view(), name='dispute_resubmission'),
    url(r'^confirm-wallet-to-vault/$', ConfirmWalletToVault.as_view(), name='confirm_wallet_to_vault'),
    
    url(r'^vault-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        WalletToVaultEmailConfirm.as_view(), name='vault_confirm'),
    url(r'^vault-transactions/$', VaultTransactionListView.as_view(), name='vault_transaction_list'),
    url(r'^vault-to-wallet/$', VaultToWalletView.as_view(), name='vault_to_wallet'),
    url(r'^vault-list/$', ListVaultView.as_view(), name='vault_list'),
    
    #pending order urls
    url(r'^cancel-pending-order/(?P<pk>\d+)/$', CancelPendingOrderView.as_view(), name='cancel_pending_order'),

    # records urls
    url(r'^get-user-balance/', GetUserBalanceTransactionView.as_view(), name='get_user_balance'),

    # order urls
    url(r'^stop-limit-order/$', OrderView.as_view(), name='stop_limit_order'),
    url(r'^depthchart/$', AjaxDepthChartView.as_view(), name='depthchart'),
    url(r'^buy-order-list/$', BuyOrderList.as_view(), name='buy_order_list'),
    url(r'^sell-order-list/$', SellOrderList.as_view(), name='sell_order_list'),
    url(r'^delete-order/(?P<pk>\d+)/$', DeleteOrderView.as_view(), name='delete_order'),

    # accept order urls
    url(r'^accept-order/', AcceptOrderView.as_view(), name='accept_order'),
    url(r'^confirm-order/', ConfirmFiatTransactionsView.as_view(), name='confirm_fiat_pendings'),
    url(r'^confirm-request-order/', ConfirmRequestFiatTransactionsView.as_view(), name='confirm_request_pendings'),
    url(r'^cancel-request-order/', CancelRequestFiatTransactionsView.as_view(), name='cancel_requestcrypto_order'),
    url(r'^cancel-request-fiat-order/', CancelAcceptFiatTransactionsView.as_view(), name='cancel_requestfiat_order'),
    url(r'^update-otc-order/', UpdateOtcOrderView.as_view(), name='update_otc_order'),

    #notification urls
    url(r'^notifications/$', NotificationListView.as_view(), name='notifications'),

    #report
    url(r'^report/$', DownloadReport.as_view(), name='report'),
    url(r'^ajax-order-book/$', AjaxOrderBookView.as_view(), name='ajax_order_book'),
]

cryptocurrency/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.static import serve
from apps.bitcoin_crypto.views import IndexView, WelcomeView, OtcWelcomeView
from .utils import ProtectServe

from background_task import background

@background()
def check_table():
    # lookup user by id and send them a message
    # user = User.objects.filter()
    print("this is check table scheduler ======== ")


# check_table(repeat=5)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crypto/', include('apps.bitcoin_crypto.urls', namespace='coins')),
    url(r'^fees/', include('apps.fees.urls', namespace='fees')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^auth/', include('apps.authentication.urls')),
    url(r'^dashboard/', WelcomeView.as_view(), name='welcome'),
    url(r'^otcdashboard/', OtcWelcomeView.as_view(), name='welcomeotc'),
    url(r'^exchange/', TemplateView.as_view(template_name='theme/exchange.html'), name='exchange'),
    url(r'^$', OtcWelcomeView.as_view(), name='index'),
    # url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], ProtectServe.as_view(), {'document_root': settings.MEDIA_ROOT}),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.db.models.signals import post_save
from django.dispatch import receiver

import pycountry


COUNTRY_NAME_LIST = sorted([(item.alpha_2, item.name) for item in list(pycountry.countries)], key=lambda country: country[1])

DOCUMENT_TYPE = (
    ('id', _('ID Card')),
    ('pan', _('Pan Card'))
    )

STATUS =(
        ('not-verified', 'Not Verified'),
        ('processing','Processing'),
        ('verified','Verified'),
        ('rejected','Rejected')
    )


class User(AbstractUser):
    phone_number = models.CharField(max_length=20, blank=True, default="", unique=True)
    agree = models.BooleanField(default=False)
    sms_otp = models.BooleanField(default=False)
    google_2fa = models.BooleanField(default=False)
    google_2fa_key = models.CharField(max_length=20, blank=True, null=True)
    change_password_date = models.DateField(default=None, null=True, blank=True)
    kyc_verified = models.CharField(max_length=20, default='not-verified', choices=STATUS)


@receiver(post_save, sender=User)
def save_password(sender, **kwargs):

    instance = kwargs['instance']
    print('saving previous password')
    print(instance)
    if not PreviousPassword.objects.filter(password=instance.password).exists():
        previous_password_count = PreviousPassword.objects.filter(user=instance).count()

        if previous_password_count >= 3:
            oldest_passwords = list(PreviousPassword.objects.filter(user=instance
                ).order_by('id')[:(previous_password_count-2)].values_list("id", flat=True))

            deleted = PreviousPassword.objects.filter(pk__in=oldest_passwords).delete()
            print(deleted)

        PreviousPassword.objects.create(user=instance, password=instance.password)
    else:
        print('password exists in previous')


class AccessLog(models.Model):
    user = models.ForeignKey(User)
    ip = models.CharField(max_length=500, blank=True, default="")
    device = models.CharField(max_length=500, blank=True, default="")
    os = models.CharField(max_length=500, blank=True, default="")
    time = models.DateTimeField(editable=False, default=timezone.now)

    def __str__(self):
        return self.user.username+"-"+self.device


class PreviousPassword(models.Model):
    """
        holding previous and current password hash of all users
    """
    user = models.ForeignKey(User)
    password = models.CharField(max_length=128)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='get_user_profile')
    full_name = models.CharField(max_length=200, blank=True, default="")

class KYCUpload(models.Model):
    user = models.OneToOneField(User, related_name='get_user_details')
    document_type = models.CharField(max_length=128, choices=DOCUMENT_TYPE)
    document_number = models.CharField(max_length=128, blank=True, default="")
    front_page = models.ImageField()
    back_page = models.ImageField()

    def __str__(self):
        return self.user.first_name


# ACCOUNT_TYPE_LIST = (
#         ('checking', 'Checking'),
#         ('saving', 'Saving')
#     )

class BankAccount(models.Model):
    """
        user bank accounts details for wire tranfer
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bank_name = models.CharField(max_length=128, verbose_name=_('Bank Name'))
    account_holder_name = models.CharField(max_length=128, verbose_name=_('Your name on your bank account'))
    # account_type = models.CharField(max_length=50, choices=ACCOUNT_TYPE_LIST)
    account_number = models.CharField(max_length=30, verbose_name=_('Bank Account Number'))
    verified = models.BooleanField(default=False)

class PaypalAccount(models.Model):
    """
        user paypal account detail
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    paypal_address = models.CharField(max_length=128, verbose_name=_('Paypal address'))
    verified = models.BooleanField(default=False)

class WechatAccount(models.Model):
    """
        user wechat account detail
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    wechat_account = models.CharField(max_length=128, verbose_name=_('Wechat account'))
    wechat_qr = models.ImageField(upload_to = "static/qr_uploads")
    verified = models.BooleanField(default=False)

class AlipayAccount(models.Model):
    """
        user alipay account detail
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    alipay_number = models.CharField(max_length=128, verbose_name=_('Alipay account'))
    alipay_name = models.CharField(max_length=128, verbose_name=_('Alipay account'))
    alipay_qr = models.ImageField(upload_to = "static/qr_uploads")
    verified = models.BooleanField(default=False)

class ComplaintsAndRequest(models.Model):
    """
        Contact form for users request and complaints
    """
    user = models.ForeignKey(User, related_name='get_the_user_requests')
    subject = models.CharField(max_length=255)
    descrption = models.CharField(max_length=1000)
    is_fixed = models.BooleanField(default=False)
    fixed_by = models.ForeignKey(User, related_name='get_admin_fixed_complaints', null=True, blank=True)

    def __str__(self):
        return self.user.email

templates/authentication/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}
{% if request.user.is_authenticated %}
<div style="padding-top: 5em"></div>
{% else %}
<div style="padding-top: 7em"></div>
{% endif %}
<div class="container">
    <h1 class="pb10">{% trans "Contact Us" %}</h1>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success">
        <strong>{% trans "Success" %}!</strong>
        &nbsp;{{ message }}
    </div>
    {% endfor %}
    {% else %}
    <div class="alert alert-warning fade in">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong>{% trans "Tips" %} :</strong> {% trans "Feedback and responses are in your Email" %};
    </div>
    {% endif %}
    <form action="{% url 'contact_us' %}" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_email">{% trans "TixonExchange Account Email" %}</label>
            {% trans "Enter email" as ph %}
            {% render_field form.email  class="form-control" aria-describedby="emailHelp" placeholder=ph %}"
            <small id="emailHelp" class="form-text text-muted">{% trans "We'll never share your email with anyone else" %}.</small>
        </div>
        <div class="errorlist" style="padding-left:5px">
            {{ form.email.errors|striptags }}
        </div>
        <div class="form-group">
            <label for="id_subject">{% trans "Subject" %}</label>
            {% trans "eg: Password change issue" as ph1 %}
            {% render_field form.subject  class="form-control"  placeholder=ph1 %}
        </div>
        <div class="errorlist" style="padding-left:5px">
            {{ form.subject.errors|striptags }}
        </div>
        <div class="form-group">
            <label for="id_descrption">{% trans "Description" %}</label>
            {% trans "Do not exceeds more than 100 words" as ph2 %}
            {% render_field form.descrption  class="form-control"  placeholder=ph2 %}
        </div>
        <div class="errorlist" style="padding-left:5px">
            {{ form.descrption.errors|striptags }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary ">{% trans "Submit" %}</button>
        </div>
    </form>
</div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/authentication/kyc_resubmission.html
{% extends 'base.html' %} 
{% load static %}
{% load transaction_status %} 
{% load i18n %}
{% block title %}{% trans "Resubmit KYC Details" %}{% endblock title %}

{% block content %}
    <div class="send-coin ">
        <div class="container">
            <h2 class="Ubuntu mb20">{% trans "Resubmit KYC Details" %}</h2>
            <div class="row mb50 send-coin-wrap">
                <div class="row m0">
                    <h4 class="m30"> <b>{% trans "KYC Details" %}</b> </h4>
                    <div class="row m0 wallet-details">
                        <div class="col-sm-6">
                            <img class="d-inline-block" src="{% static 'img/bitcoin.png' %}" width="40px">
                            <p class="d-inline-block mf10"><b>BTC</b></p>
                        </div>
                        <div class="col-sm-6">
                            <p class="m10 f-medium" ><b>{% trans "User" %}:</b> {{user.get_user_profile.full_name}} {{user.get_user_profile.last_name}}</p>
                            <p class="m10 f-medium" ><b>{% trans "User Email" %}:</b> {{user.email}}</p>
                        </div>
                    </div>
                    <div class="">
                        <h4 class="m30"><b>{% trans "FeedBack" %}</b></h4>
                        <form method="post" action="." >
                            {% csrf_token %}
                            <div class="form-group">
                                 <textarea name="feedback" placeholder="{% trans "Enter Feedback" %}" class="form-control" rows="10" cols="30" style="resize: none;" required></textarea>
                                 <div class="errorlist">{{feedback_error}}</div>
                            </div>

                            <div align="right">
                                <a href="{% url 'welcome' %}" type="button" class="btn-back btn m20 pull-left"> <i class="fas fa-arrow-left"></i> {% trans "BACK TO DASHBOARD" %}</a>
                                <button type="submit" id="submit_amount" class="btn-main btn m20" >  {% trans "CONFIRM REJECT" %} </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}{% endblock %}

{% block script %}
{% endblock script %}

templates/authentication/profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Profile" %}{% endblock %}

{% block content %}
<div class="profile">
    <div class="container">
        <div class="row m0">
            <div class="col-sm-4">
                <div class="profile-img">
                    <h4>{% trans "Profile" %}</h4>
                    <div class="p-relative">
                        <img src="{% if not user.get_user_address_details.photo_selfi.url %}
                                    {% static 'img/user.png' %}
                                  {% else %}
                                    {{ user.get_user_address_details.photo_selfi.url }}
                                  {% endif %}" width="150px" height="150px" class="img-circle">
                        <!--<div class="cam-pic"> <i class="fas fa-camera"></i> </div>-->
                        <h3><b>{{user.get_user_profile.full_name}}</b></h3>
                    </div>
                </div>
            </div>
            {% if not request.user.is_superuser %}
            <div class="col-sm-8">
                <div class="profile-top">
                    <h4 class="m40"><b>{% trans "Your profile status" %}</b></h4>
                    <p>{% trans "This user profile has considered in" %} {{request.user.get_kyc_verified_display|lower}} {% trans "state" %}. {% trans "For any modification in profile details please contact the site administrator" %}.</p>
                    {% if request.user.kyc_verified == 'not-verified' %}
                        <a href="{% url 'kyc_upload' %}" class="btn-main btn m20 "> <i class="" style="color: #0fd800;"></i> {% trans "Verifiy" %}</a>
                    {% elif request.user.kyc_verified == 'processing' %}
                        <button class="btn-main btn m20 "> <i class="fas fa-sync" style="color: #f3bc18;"></i> {% trans "Processing" %}</button>
                    {% elif request.user.kyc_verified == 'verified' %}
                        <button class="btn-main btn m20 "> <i class="fas fa-check" style="color: #0fd800;"></i> {% trans "Verified" %}</button>
                    {% elif request.user.kyc_verified == 'rejected' %}
                        <button class="btn-main btn m20 "> <i class="fas fa-close" style="color: red;"></i> {% trans "Rejected" %}</button>
                    {% endif %}
                </div>
            </div>
            {% endif %}
            <div class="col-sm-12">
                <div class="profile-bottom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#home">{% trans "Personal details" %}</a></li>
                        <li><a data-toggle="tab" href="#menu1">{% trans "Documents" %}</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="home" class="tab-pane fade in active">
                            <div class="row m0">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="grey">{% trans "Full Name" %}</label>
                                        <h3 class="m0">{{user.get_user_profile.full_name}}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="menu1" class="tab-pane fade">
                            <div class="row m0">
                                <h2 class="Ubuntu mf15">{% trans "Photo ID" %}</h2>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="grey">{% trans "Type of document" %}</label>
                                        <h3>{{user.get_user_details.get_document_type_display}}</h3>
                                    </div>
                                    <div class="form-group">
                                        <label>{% trans "Front of document" %}</label>
                                        <img src="{{user.get_user_details.front_page.url}}" width="100%">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="grey">{% trans "IC/Passport Number" %}</label>
                                        <h3>{{user.get_user_details.document_number}}</h3>
                                    </div>
                                    <div class="form-group">
                                        <label>{% trans "Back of document" %}</label>
                                        <img src="{{user.get_user_details.back_page.url}}" width="100%">
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div style="text-align:right; padding:20px;">
                    {% if request.user.is_superuser %}
                        <a href="{% url 'kyc_list' %}" style="width:200px;margin-right:15px;" class="btn btn-success">{% trans "Back To KYC List" %}</a>
                        {% if user.kyc_verified == 'processing' %}
                            <a href="{% url 'kyc_approve' pk=user.pk %}" style="width:200px" class="btn btn-primary">{% trans "Approve" %}</a>
                        {% endif %}

                        {% if not user.kyc_verified == 'rejected' %}
                        <a href="{% url 'kyc_reject' pk=user.pk %}" style="width:200px" class="btn btn-danger">{% trans "Reject" %}</a>
                        {% endif %}
                        
                    {% else %}
                        <a href="{% url 'welcome' %}" style="width:200px;margin-right:15px;" class="btn btn-success">{% trans "Back To Dashboard" %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

{% block script %}
  <script>
    $('#home,#tag').on('hover focus',function(){
        alert();
    })
  </script>
{% endblock %}